libgnomekbd: remove it
[WIND: US21002]

Fix this error when "bitbake world":

ERROR: Required build target 'libgnomekbd' has no buildable providers.
Missing or unbuildable dependency chain was: ['libgnomekbd', 'libxklavier']

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>