libreport: fix compile failure
Since gcc upgraded, we tweak comparison to fix the failure:
...
error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
      || ((op != OPT_list_events) && (!(opts & OPTMASK_need_arg) == argc))
...

Rally: US64341
Issue: LIN8-850

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>