libreport: remove doc to fix do_install failed
There was a failure at do_install time:
...
| xmlto man report_event.conf.xml 2>&1
| I/O error : Attempt to load network entity
http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| warning: failed to load external entity
"http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
|compilation error: file /tmp/xmlto-xsl.vEpxaD line 4 element import
|xsl:import : unable to load
http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
...
|  /usr/bin/install -c -m 644 ./report_event.conf.5
'tmp/work/x86_64-wrs-linux/
libreport/2.0.10-r0/image/usr/share/man/man5'
| /usr/bin/install: cannot stat './report_event.conf.5': No such file or
directory
| make[2]: *** [install-man5] Error 1
...

The reason was invoking xmlto failed, so remove module doc is a workaround.

[WIND: US21002]

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>