usermode: add util-linux to DEPENDS [ LIN8-672 ]
There is a compiling failure of usermode:
...
|/usermode/1.108-r0/usermode-1.108/usermount.c:55:25: fatal error:
blkid/blkid.h: No such file or directory
| #include <blkid/blkid.h>
|                         ^
|compilation terminated.
...

The blkid.h was belonged to util-linux, so we add util-linux to
usermode's DEPENDS.

Issue: LIN8-672

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>