usermode: fix do_configure and do_compile
Issue: US43477

It requires pkgconfig and intltool-native, otherwise errors:
do_configure:
conftest.c:15:28: fatal error: ac_nonexistent.h: No such file or directory

do_compile:
Makefile:1572: *** missing separator.  Stop.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>