anaconda: remove libreport-python RDEPENDS until it builds with gcc5
libreport fails to build:
.../libreport/2.0.10-r0/libreport-2.0.10/src/cli/cli.c:108:65:
    error: logical not is only applied to the left hand side of comparison
    [-Werror=logical-not-parentheses]

Remove libreport-python from anaconda's list of runtime dependencies
until it builds since the wrinstaller image should still build
without libreport.

libreport's error is tracked by defect: LIN8-850

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>