iscsi-initiator-utils: replace 'inline' with 'static inline' for gcc 5.x
gcc 5.x defaults to -std=gnu11 instead of -std=gnu89 which causes
semantics for inline functions changes.

The standalone 'inline' causes error with gcc 5 such as:

git/testcases/kernel/syscalls/kill/kill10.c:355: undefined reference to `k_sigaction'

Replace inline with static inline to be compatible with both gcc 4 and 5.

Rally: US64341
Issue: LIN8-849

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>