anaconda: add missing include sys/resource.h
Issue: LIN8-739

Fix the error:
loader.c:1782:12: error: variable 'corelimit' has initializer but incomplete type
loader.c:1782:33: error: 'RLIM_INFINITY' undeclared (first use in this function)
loader.c:1783:19: error: 'RLIMIT_CORE' undeclared (first use in this function)

This is exposed after the glibc is upgraded from 2.21 to 2.22.

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>