dmraid: fix parallel compile issue
If run rule $(TARGETS) before $(SUBDIRS), there is a compile failure:
...
tools/dmraid.c:12:27: fatal error: dmraid/dmraid.h: No such file or directory
 #include <dmraid/dmraid.h>
...

Rule $(TARGETS) is not necessary, all done in $(SUBDIRS).

The $(LIB_EVENTS_SHARED) requires $(LIB_SHARED), add missing dependence.

Issue: LIN9-1347

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>