anaconda: remove iscsi-initiator-utils until it builds
iscsi-initiator-utils fails to build:
In function `ipv6_find_longest_match':
.../open-iscsi-2.0-873/iscsiuio/src/uip/ipv6.c:623: undefined reference to `best_match_bufcmp'

Remove iscsi-initiator-utils from anaconda's list of dependencies
until is is resolved since anaconda still builds and the
glibc-small configuration also conpletes successfully.

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>